### PR TITLE
Re-implement the client in C, and other modifications

### PR DESCRIPTION
**Pull request by ccrusius**
A few changes I have made:

- Re-implement the client in C, removing the dependency for socat, and avoiding spawning up a shell. Keeps with the "lightweight" theme.
- Bind Ctrl+ and Ctrl- for on-the-fly font size changes.
- Disable a few things if VTE is too old, to make it compile in Ubuntu 16.04.
- Parameterize the configuration so I can easily reconfigure things via a script.

### CODE REVIEW

**Comment by vain** [comment]
Thank you for your work.

I'm very curious about that last point: "Parameterize the configuration
so I can easily reconfigure things via a script." What's the scenario
here? An automated build process feels like overkill for a rather simple
tool like xiate. Even a simple precompiled package isn't very useful,
since there is no runtime configuration. It's similar to tools like dwm
or st: You *might* want to provide a "default package", but users are
usually expected to grab the source code, create their own config.h or
even edit the actual C source code, and then compile a binary.

So, I'm curious to hear what you have in mind. :)

What's the reasoning behind reimplementing the client in C? Did you
encounter any issues with socat or did you have performance problems?

Rewriting the client in C is a bit problematic: a) It's more code for
*me* to maintain. That shell script was simple and socat did all the
dirty socket work. Plus, a C client is much more prone to bugs (let's
face that). b) I still hope that I can get rid of the client/server
model some day. It's a hack. I only implemented it this way because
VTE+Gtk is slow to start up. But maybe those libraries get faster or my
computers get faster. I'd really love to have one process per terminal
window, because it's more robust. If there *was* a crash in xiate or,
worse, in VTE or Gtk or Glib, then currently *all* your terminal windows
are gone. All of them! This is very bad.

I even thought about kicking the client/server model *today*, even if
it's slow.

About "Disable a few things if VTE is too old, to make it compile in
Ubuntu 16.04": Phew, I don't think I can do that. That change implies
that Ubuntu is "supported". Thing is, I don't use Ubuntu and I can't
follow their package versions just for xiate. If I were to implement a
new feature, I'd have to check if the version of VTE in Ubuntu supports
$foo and $bar. Plus, eventually, the code would be riddled with ifdefs.

Right now, it says that you need VTE 0.44. This might even be wrong. I
use 0.46, so I should bump that requirement.

**Comment by ccrusius** [comment]
One by one then:

- The parameterized configuration is for automated install scripts from source, which I use in systems I maintain. I'm not crazy about that one either, it just happens to be there, and I can't create a pull request without it. It can be removed. In the end, though, I will probably one day add code to make the server configurable via Xresources or CLI options. This does not make it "heavy," but makes it "packageable," which means it would help more people who are looking for something like this (and there are many).
- The C implementation for the client seems natural to me. Why spawn a full shell, then socat, then what not, just to set up a simple socket? By using the GLib functions, which you already do in the server itself, the C code turns out to be very simple. (That's another reason right there: use the same underlying socket infrastructure for both client and server.)
- I'm fine with the client/server thing. It is used in other places for the same reason. I don't even care about it crashing, since I'm always inside `tmux` anyway, and set scrollback lines to zero. This is similar to what [st](http://st.suckless.org/) does (and which I would use, if I could easily change font sizes on the fly).
- The Ubuntu "support" doesn't need to be sold as "official support." On the other hand, having something that does not compile in one of the most popular distributions is not really helping people who are looking for a lightweight terminal. My changes are also not Ubuntu-specific, so hopefully this allows for compilation in other distributions that do not have up-to-date VTE.

Anyway, let me know - if you think these changes go too much against the grain of what you are trying to accomplish, I'll just "officially fork" and go my own way. In particular, though, I do think what you have is very close to what lots of people are looking for, it just needs a few extra things (on top of what I already did):
- Run-time configuration, instead of compile-time. This allows for a standard package to be produced, and people can start the server with their own settings at will.
- Non-patched compilation on the main distributions (Ubuntu, CentOS, etc), to make the packagers life easier.

**Comment by ccrusius** [comment]
A question: while browsing the sources for `libvte`, I found they have a sample terminal application. It looks similar to `xiate`, although `xiate` is stripped down in some places, and adds functionality in others. Is that what you based `xiate` on?

**Comment by ccrusius** [comment]
Since I suggested, I implemented it: on my `master` branch, configuration can now be done via `Xresources`, and that is how I have set up my systems (it somewhat works out of the box, since the values are compatible with those for `rxvt`).

**Comment by vain** [comment]
Dude, you should go ahead and fork. Not because I'm grumpy -- but because I'm impressed by your speed and ambition. :) I'll probably only slow you down.

And you clearly have different goals. My xiate is rather minimalistic (regarding the amount of code) and works very well *for me* (in terms of functionality and maintenance). But, yeah, it's not a product for the masses. Probably never will be. I simply don't have the time/ressources to create and maintain something like that. Not in the Gtk/Glib/VTE world where things change quite often.

I'm curious to see what you're going to create!

> A question: while browsing the sources for libvte, I found they have a sample terminal application. It looks similar to xiate, although xiate is stripped down in some places, and adds functionality in others. Is that what you based xiate on?

No, it was written from scratch, but it's very likely that I had a look at `vteapp.c` at some point. And I did have a look at the source code of other VTE terminals like sakura or roxterm -- that was very helpful.

Oh, this might be interesting for you as well: About a month after I wrote xiate, I found [taterm](https://github.com/t-8ch/taterm) by @t-8ch. Never heard of that before. It also uses a client-server model. It's written in Vala, though, and uses DBus for IPC.

**Comment by ccrusius** [comment]
Alright, will do then - thanks!

**Pull request closed without merging**
